#!/usr/bin/env python3

import amulet
import time

d = amulet.Deployment(series="trusty")

d.add('apache2')
d.add('logrotate')

d.relate('apache2:juju-info', 'logrotate:juju-info')

# Don't forget to expose using d.expose(service)

try:
    d.setup(timeout=900)
    d.sentry.wait()
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    raise

unit = d.sentry['apache2/0']

# Check logrotate.d exists
if "logrotate.d" not in unit.directory_contents("/etc")["directories"]:
    amulet.raise_status(amulet.FAIL, msg="/etc/logrotate.d was not created")

# Check for config file changes
d.configure("logrotate", {"logfiles": '{"amulet-test1": {"path": "/var/log/apache2/*.log"}}'})
time.sleep(20)
if "amulet-test1" not in unit.directory_contents("/etc/logrotate.d")["files"]:
    amulet.raise_status(amulet.FAIL, msg="logrotate.d file was not created")
